### ISSUE TITLE
consumerParmeters don't specify `type` or `required`

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/docs#1004]
**Describe the bug**
The `consumerParameters` defined in the [DDO Spec](https://github.com/oceanprotocol/docs/blob/main/content/concepts/did-ddo.md#consumer-parameters) don't specify element `type` or whether a given element is `required`.

> It's an array of elements, each element object defines a field.
> An element looks like:
> 
> ```json
> {
>   "name": "hometown",
>   "type": "text",
>   "label": "Hometown",
>   "required": true,
>   "description": "What is your hometown?",
>   "default": "Nowhere",
>   "options": []
> }
> ```
> 
> where:
> 
> - name = defines the parameter name (this is sent as HTTP param or key towards algo)
> - type = defines the form type (text, number, select, boolean)
> - label = defines the label which is displayed
> - required = if this field is mandatory to have a consumer input.
> - default = default value
> - description = description of this element
> - options = for select types, a list of options

**Expected behavior**
A table with columns: 

Attribute | Type | Required | Description
-- | -- | -- | --

**Comment by alexcos20** [comment]
you have the list above, what the point of a new table? :)

**Comment by DMats** [comment]
We discussed this issue at yesterday's daily stand-up. We determined that all of the consumer parameters are required except `options` which is only needed when `type == select`.

@alexcos20 I think a table is required to stay consistent with the rest of the document.  Both @calina-c And I weren't sure if all of these were required so I think it's best to spell it out explicitly.

I can make the PR.
