### ISSUE TITLE
Broken link on the Provider API page

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1007]
**Describe the bug**

**To Reproduce**
1. Go to the [provider API specification page](https://docs.oceanprotocol.com/references/provider/)
2. Click on [Docs: Provider API Reference](https://docs.oceanprotocol.com/references/ocean_provider/)

**Expected behavior**
I'm not sure where this link is supposed to go - maybe we can just delete it?

**Screenshots**
![docs - provider link broken - 2022-05-27_16-38](https://user-images.githubusercontent.com/20739535/170732907-ed35f058-9e72-4ba8-9749-66a475cc62ac.png)

**Comment by jamiehewitt15** [comment]
Thanks @akshay-ap

**Comment by akshay-ap** [comment]
This is now fixed.
