### ISSUE TITLE
Add additional information on the asset pricing page

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1017]
For the [asset pricing page](https://docs.oceanprotocol.com/concepts/asset-pricing/), let's add more information on the Dynamic Pricing schema to cover these questions as well.

- [x] What happens with the data asset price when liquidity is added/removed from the pool?
- [x] What happens with the data asset price when datatokens are bought? 
- [x] What happens with the data asset price when somebody sells a datatoken?
- [x] What happens with the data asset price when somebody consumes it?

**Comment by jamiehewitt15** [comment]
Everything is ticked on the checklist, any reason this hasn't been closed?

**Comment by AnaLoznianu** [comment]
Because the PR is not merged yet: https://github.com/oceanprotocol/docs/pull/1024
