### ISSUE TITLE
Upgrade to gatsby v4

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#1018]
**Is your feature request related to a problem? Please describe.**
Current docs site is running on outdated Gatsby v2 version. We should consider upgrading to v4 (latest version).
There are breaking changes in the 

**Describe the solution you'd like**
- [ ] Step 1: Upgrade gatsby v2 to v3
- [ ] Step 2: Upgrade gatsby v3 to v4

**Describe alternatives you've considered**
Discuss if we should use Gatsby or move to other docs hosting service #981

**Additional context**
NA

**Comment by jamiehewitt15** [comment]
We won't do this. New plan is to move to gitbook
