### ISSUE TITLE
Updating Docs vs New Version

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1031]
I'm opening this issue to start a discussion on the future of the docs. The tech in this repo is currently [outdated](https://github.com/oceanprotocol/docs/pull/1030#issuecomment-1161669553) and hasn't been properly maintained, so we can either start again or we have a lot of work to do in updating this repo.

If we choice to start again, some of the available options are:

1. Use an out-of-the-box documentation site builder such as https://readthedocs.org/ or https://www.gitbook.com/
2. Fork an existing documentation site that has been properly maintained e.g. https://github.com/graphprotocol/docs
3. Start a fresh new site and build it using the tech of our choice

**Comment by jamiehewitt15** [comment]
Closing this as a decision has been made: we will stop using this repo and create a new version of the docs

**Comment by kremalicious** [comment]
just to be clear, we most likely will continue using this repo, it will be just reduced to the content which then gets read out by some 3rd party tool

**Comment by jamiehewitt15** [comment]
> just to be clear, we most likely will continue using this repo, it will be just reduced to the content which then gets read out by some 3rd party tool

I've updated my message to reflect this
