### ISSUE TITLE
Add application sanitization information

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1035]
Let's add some information on our docs to inform our users that on the blockchain basically everything can be added. Whoever writes applications, needs to sanitize on their end the responses from our backend components. 

This can be part of other tutorials and not a page in itself.

**Comment by jamiehewitt15** [comment]
Possibly we could create a page on security and this could be one of the sections

**Comment by AnaLoznianu** [comment]
This can be part of other tutorials and not a page in itself.

**Comment by AnaLoznianu** [comment]
Done in Docs V2
