### ISSUE TITLE
Page with projects built on top of OCEAN core product

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1036]
Let's build a page with a list of projects built on top of Ocean.

Criteria for projects to be added:
* open source code 
* have a working demo(whatever this means) 

Examples:
* Alga app 
* DataX

**Comment by trentmc** [comment]
I think this is great!

I was thinking this too.

Here's an example for scikit learn:
https://scikit-learn.org/stable/auto_examples/index.html

It would be cool if we had a 3x3 or 4x4 gallery like this.

We can include some existing projects:
- ALGA data wallet (though not open source)
- DataX
- other?

**Comment by AnaLoznianu** [comment]
@akshay-ap @jamiehewitt15 What about adding a reference towards the datawhale site?
https://datawhale.ai/learn/ or https://datawhale.ai/tutorials/ for learning/tutorials

**Comment by jamiehewitt15** [comment]
Yeah, we should have a list of external tutorials somewhere in the docs. There are also others that can be included in the list:

- [Ocean Academy](https://www.oceanacademy.io/)
- [DeltaDAO Ocean tutorial](https://academy.delta-dao.com/topic/ocean-protocol-basics#deep-dive-into-tech)
- [Gaia X MVP tutorial](https://portal.minimal-gaia-x.eu/tutorial)

**Comment by jamiehewitt15** [comment]
By the way, how about if this page is maintained by the Nile team @malvonme @idiom-bytes?

**Comment by AnaLoznianu** [comment]
The Nile team is pretty stretched at the moment. Let's keep it in the Danube team
