### ISSUE TITLE
New Content Categories

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1039]
I'm proposing that we organise the content into the following categories: 

## Orientation
This is to cover all of the entry level web3 topics. We can port over the following pages from the existing docs:
- Wallet Basics
- Set Up MetaMask Wallet  
- Use Your Wallet to Manage OCEAN Tokens

## Core Concepts
This should be an explanation of what ocean does and how it does it, including the architecture. The folowing pages can be ported over from the existing docs:
- Introduction
- Architecture Overview
- Data NFTs and Datatokens
- Data NFTs and datatoken roles
- Supported Networks
- Fees
- Asset pricing
- DID & DDO

## Using Ocean Market
The tutorials on how to use Ocean Market can be put into this section, including the videos. Pages can be ported from existing docs:
- Publish a data asset
- Publish assets using hosting services
- Download a data asset
- Swap datatokens
- Add liquidity to liquidity pools
- Tutorials on how to use compute to data

## Building with Ocean
All the guides that involve any coding will go in this section:
- New page on how to build out the basic user stories. This page can combine javascript and python code examples.
- How to fork Ocean Market (from marketplace launchpad)
- How to create an isolated marketplace (new page)
- How to setup and host your own provider (new page)
- How to create you own compute to data environment
- How to use the RBAC server (new page)
- Ways to Contribute
- Projects using Ocean Protocol

## API References
A page of API references for each of the following services:
- Aquarius
- Provider
- subgraph
- RBAC

**Comment by jamiehewitt15** [comment]
Welcoming feedback @AnaLoznianu @akshay-ap @kremalicious @mihaisc

**Comment by akshay-ap** [comment]
How about a section on **Using Libraries**?

Using Libraries:
- Creating dataNFT/datatoken
- Publish dataset/alogrithm
- Managing allowed algorithms
- Downloading asset
- Managing pools
- Starting compute job

and then each section will have ocean.js/ocean.py examples with some explanation.

**Comment by akshay-ap** [comment]
How about adding this in **Building with Ocean**:

How to host own Aquarius?

**Comment by mihaisc** [comment]
Agree, Building with Ocean and Using Libraries is the same thing.
