### ISSUE TITLE
Integrate tutorial videos

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1047]
Add Liquidity: https://www.youtube.com/watch?v=Ry_x1mqTj8w
Purchase: https://www.youtube.com/watch?v=gF48nzaMgXA
Swap: https://www.youtube.com/watch?v=7UTegQR4Zng

**Comment by jamiehewitt15** [comment]
We can reopen this when we have new tutorial videos but for the moment there is nothing to do here
