### ISSUE TITLE
Update info on AMM pools and LPs

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1060]
As we are moving away from the dynamic pricing schema and the AMM pools, we need to update our docs. 

I identified the following pages that need updates(Please add more if I missed something)
- [x] Remove "Manage pools": https://docs.oceanprotocol.com/concepts/introduction/
- [x] Remove "automatic price discovery": https://docs.oceanprotocol.com/concepts/architecture/
- [x] Remove LPs info: https://docs.oceanprotocol.com/concepts/datanft-and-datatoken/
- [x] Remove LPs and AMM info: https://docs.oceanprotocol.com/concepts/fees/
- [x] Remove dynamic pricing: https://docs.oceanprotocol.com/concepts/asset-pricing/
- [x] Remove info on LPs: https://docs.oceanprotocol.com/tutorials/marketplace-introduction/
- [x] Update screenshots and replace the dynamic pricing schema step with fixed-rate exchange: https://docs.oceanprotocol.com/tutorials/marketplace-publish-data-asset/
- [x] Update screenshots: https://docs.oceanprotocol.com/tutorials/marketplace-download-data-asset/
- [x] Remove - https://docs.oceanprotocol.com/tutorials/marketplace-swap/
- [x] Remove - https://docs.oceanprotocol.com/tutorials/marketplace-add-liquidity/

For the API references, we will need initially to update our components and then the docs.

@akshay-ap as we discussed yesterday, let's do these changes for Gitbook. I know that it's the same markdown file but let's not focus on that now and get ready to make gitbook docs public.

cc @trentmc

**Comment by akshay-ap** [comment]
Closing as this is done.
