### ISSUE TITLE
Tutorial/demo on how to remove liquidity via etherscan

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1068]
Example: https://balancer.gitbook.io/balancer/guides/withdrawing-liquidity-via-etherscan

**Comment by AnaLoznianu** [comment]
First, let's try to have the instructions using gist

**Comment by mihaisc** [comment]
Didn't see the issue, so copy paste from slack
 for removing in etherscan we just need to call exitswapPoolAmountIn with pool id, user pool shares , and we can ask everyone to use 1 for the last field min amount out . The only problem is how the user finds out how many shares he has. These are erc20 tokens in his wallet

pool shares in the wallet look like this
![image](https://user-images.githubusercontent.com/26000280/179744043-5a63da8e-43c6-4579-ab25-1cf5d6d1e9bd.png)


we can create a subgraph query and tell them to replace the account address in that query

it has a nice UI so it should be doable

**Comment by kremalicious** [comment]
Moved to market repo for now so we have something https://github.com/oceanprotocol/market/pull/1617

Fine to move this over later once Gitbook docs are released

**Comment by akshay-ap** [comment]
Add a page here on removing liquidity using etherscan: 
![image](https://user-images.githubusercontent.com/16358982/180988299-d01a0116-a26e-441f-ac6b-5485ffe51a19.png)

**Comment by jamiehewitt15** [comment]
I've added high priority as ideally this would be included in the new docs when we launch on Monday
