### ISSUE TITLE
Explain what H2O is & where to get it

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1093]
**Is your feature request related to a problem? Please describe.**

Explain what H2O is. When https://github.com/oceanprotocol/market/pull/1516 is merged into the market we will start allowing people to use H2O in the market. We therefore need to briefly explain somewhere what this currency is and what the point of it is. 

We could create a "tokens" page that contains information on H2O and all other approved tokens, whcihc would go within the core concepts section.

Should include:
- What is H2O.
- Where can people get it from.
- Any limitations, risks, warnings etc

**Comment by mihaisc** [comment]
We have some info in the docs about h2o and psdn. Won't be focusing for now on creating more material
