### ISSUE TITLE
DID DDO page content repeated

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#1114]
**Describe the bug**
Gitbook is repeating the content in the tables in DID DDO page: https://docs.oceanprotocol.com/core-concepts/did-ddo#did

![image](https://user-images.githubusercontent.com/16358982/185422068-277d4a33-c665-4958-9098-edf36b2e38c6.png)

**To Reproduce**
1. Go to DID DDO page
2. Go to `Compute Options`

**Expected behavior**
No repetition

**Screenshots**
-

**Comment by mihaisc** [comment]
also 
![image](https://user-images.githubusercontent.com/26000280/189865430-ec591413-e94c-4a3b-8d3e-57709ad94836.png)

**Comment by mihaisc** [comment]
didn't i fix this? It looks like it's fixed, or am i missing something

**Comment by jamiehewitt15** [comment]
Yeah looks good now. That page might need other improvements but at least this issue isn't there anymore
