### ISSUE TITLE
DID & DDO page is too long and confusing

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1120]
The DID & DDO page is too long and confusing, we should tidy it up and possibly split it into different pages.

**Comment by ChristianCasazza** [comment]
Underneath the fields for compute options, the descriptions are repeated several times and make the page longer
<img width="643" alt="image" src="https://user-images.githubusercontent.com/99146900/186704515-9c28673c-57ce-463e-b733-166c921e500d.png">

**Comment by AnaLoznianu** [comment]
Related issue: https://github.com/oceanprotocol/docs/issues/1114

**Comment by AnaLoznianu** [comment]
Done in Docs V2.
