### ISSUE TITLE
Fix tables in the docs

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1132]
There are multiple tables on our docs that need a bit of cleanup. 
The problem with most of them is that the widths of all columns are the same. Even if one column needs less space(just for a checkmark). This creates a problem for the columns that need more space, making the table need a horizontal scroll. 
Example https://docs.oceanprotocol.com/core-concepts/did-ddo#metadata

**Comment by jamiehewitt15** [comment]
It seems that something odd maybe happening on the gitbook side which is messing up the tables. @MantisClone reported having trouble with this

**Comment by MantisClone** [comment]
There's a couple issues I noticed:

1. Gitbook doesn't handle code embedded in tables well. You can embed code in a table such that it looks correct in the Gitbook editor, but then when it renders or re-syncs, it gets all messed up. I've fixed the tables related to storage objects to use regular code blocks in PR #1082.
2. Gitbook injects duplicate rows in a few of the tables each time a new commit is added.

**Comment by mariacarmina** [comment]
I have created a change request directly on gitbook. I submitted for review on Gitbook and left some comments there as well. CC @AnaLoznianu

**Comment by jamiehewitt15** [comment]
> I have created a change request directly on gitbook. I submitted for review on Gitbook and left some comments there as well. CC @AnaLoznianu @jamiehewitt15

The workflow we follow on the docs is the same as all the other repos, with all change requests handled in pull requests on Github. Can you do it here next time

**Comment by AnaLoznianu** [comment]
@jamiehewitt15 Gitbook offers a great visualization tool to edit the tables. You know how difficult it is to edit tables and column lengths on markdown directly. That's why I think for this particular PR, using change requests in gitbook actually makes our life easier.

**Comment by mariacarmina** [comment]
Merged on Gitbook, we can close this
