### ISSUE TITLE
Page for partners / service providers

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#1151]
Daimler are keen to be listed somewhere in our docs as a service provider. We could have a dedicated page in our docs for this which would include Delta DAO and others. This could go in the "Building with Ocean section"

**Comment by jamiehewitt15** [comment]
Any thoughts on this? @AnaLoznianu @mihaisc

**Comment by kremalicious** [comment]
how about maintaining the actual page which was always meant for this?

https://oceanprotocol.com/collaborators

**Comment by AnaLoznianu** [comment]
We already have a page on projects that use Ocean here: https://docs.oceanprotocol.com/building-with-ocean/projects-using-ocean#oceandao-projects 
We could add them there on a new page
@kremalicious Daimler is already listed on our collaborators' page on the site. But I think we could add more tech details on the docs

**Comment by jamiehewitt15** [comment]
Do we really need both a page on the docs and the main site for partners & collaborators? I think it might be better to just have a link to the main site so that we don't end up maintaining this in both places. 

Also I realise that this issue is more or less a duplicate of: https://github.com/oceanprotocol/docs/issues/1036
