### ISSUE TITLE
Add proper specs for the ddo.state

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1159]
https://docs.oceanprotocol.com/core-concepts/did-ddo#state 

We have the state field that is stored in the NFT but currently, there are no specifications on the implications of the values there. What should be listed in the UI and what not? 
What should be retrieved by Aqua?

**Comment by alexcos20** [comment]
<html>
<body>


State | Description | Discoverable in UI | Ordering allowed | Listed under profile
-- | --| --| --
0 | Active| Yes | Yes | Yes
1 | End-of-life.| No | No| Yes
2 | Deprecated (by another asset).| No | No| Yes
3 | Revoked by publisher.| No | No| Yes
4 | Ordering is temporary disabled.| Yes | No| Yes
5 | Asset unlisted.| No | Yes| Yes


</body>
</html>

**Comment by alexcos20** [comment]
@kremalicious @AnaLoznianu  - thoughts ?

**Comment by jamiehewitt15** [comment]
So 1, 2, 3 are all the same then? So essentially in the market we can give publishers four options:

- Active (0)
- Revoked (1/2/3)
- Temporary disabled (4)
- Unlisted (5)

**Comment by jamiehewitt15** [comment]
Maybe one of the states should have a no in every column? There could be some situations where the publisher doesn't want the asset even to be shown on their profile (maybe they published it by mistake)

**Comment by alexcos20** [comment]
that's a good question.  from my view, once you revoke a dataset (1/2/3), you should not see it anymore

**Comment by jamiehewitt15** [comment]
So then the table would look like this?

| State | Description | Discoverable in UI | Ordering allowed | Listed under profile |
| ----- | ----------- | ------------------ | ---------------- | ---- |
| 0     | Active | Yes | Yes | Yes |
| 1     | End-of-life | No | No | No |
| 2     | Deprecated (by another asset) | No | No | No |
| 3     | Revoked by publisher | No | No | No |
| 4     | Ordering is temporary disabled | Yes | No | Yes |
| 5     | Asset unlisted.| No | Yes | Yes |
