### ISSUE TITLE
Launch New Template (Docs)

### ISSUE THREAD

**Issue by andreaarmanni** [oceanprotocol/docs#1186]
- Add section for new showcase in the docs
- Add video tutorial, if needed
- Create & Integrate interface through Storybook to provide interactive UX/UI examples

**Comment by mihaisc** [comment]
do we still want this? We will be adding showcase details in the site

**Comment by andreaarmanni** [comment]
A section for templates in the docs would be nice, but also not compulsory. I'd say let's keep all things in one place until are scalable then we can expan?

**Comment by mihaisc** [comment]
not doing this, not in the near future anyway. We are already adding more content in the site. Videos are not relevant and also integrating them through storybook is not a easy task. Will create another task to add links to the templates as examples ( if they are not already there)
