### ISSUE TITLE
where is the code of Dori?

### ISSUE THREAD

**Issue by monperrus** [oceanprotocol/docs#1206]
Hi! I'm reading about dori in https://blog.oceanprotocol.com/making-ocean-protocols-smart-contracts-and-it-s-governance-unstoppable-45cf99dc1b65 by @H34D

However https://github.com/oceanprotocol/dori is now 404.

Where is the code of Dori?

Thanks!

**Comment by AnaLoznianu** [comment]
Hello, Dori was used a long time ago. Since then a lot of things changed. See the ew V4 architecture here: https://blog.oceanprotocol.com/ocean-v4-overview-1ccd4a7ce150
