### ISSUE TITLE
DF: Add tips how to identify good assets to allocate to

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/docs#1212]
There are multiple users asking how they can identify the best assets to give their allocation to.
We could add info about the most important metrics and all the things users can look into to find the asset they can trust and make best use of their allocation.

**Comment by mihaisc** [comment]
@KatunaNorbert is this something you guys have on your radar? if not, i'll close it. It's nice to have but not enough resource to focus on this for the moment

**Comment by trentmc** [comment]
This isn't worth it anytime soon. Bigger fish to fry. Closing.
