### ISSUE TITLE
DF - Onboarding/Knowledge Dependency

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1220]
In V2, some of the DF pages got moved around which is great (let's iterate and try to improve).

However there are things (like veOCEAN Time-Lock and Linear Decay) mechanism that are not explained to the user until well after we have told them to lock up their OCEAN. 

Unfortunately these are things that we have to explain our users very early on so they can take that first step knowingly.

### DoD:
- [ ] Restructure the DF docs & steps just slightly, as to give the user a basic level of required knowledge before going through one-day doors.

**Comment by AnaLoznianu** [comment]
@idiom-bytes I assume we can close this as the refactor is already merged. Please re-open if you consider different
