### ISSUE TITLE
Challenge DF - Review updates

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1221]
### DoD:
- [ ] Review Challenge DF Updates
- [ ] Update intro/basics of DF to include Challenge DF considerations
- [ ] Update reward/streams/breakdown of Challenge DF
- [ ] Clean up How-Tos in order to include updates to Challenge DF, and other updates such as Delegation

**Comment by AnaLoznianu** [comment]
@idiom-bytes I assume this can be closed as the refactor is already merged. Please reopen if you consider differently
