### ISSUE TITLE
DF: move "Estimate APYs" page content into the top-level "Data Farming Rewards" page

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1233]
### Motivation

Reduce number of pages, streamline UX.

More context: https://github.com/oceanprotocol/docs/pull/1219#discussion_r1274588640

### TODOs

- [ ] Move content in the ["Estimate APYs" page](https://docs.oceanprotocol.com/rewards/user-guides/how-to-estimate-apy) into the ["Data Farming Rewards" page](https://docs.oceanprotocol.com/rewards)
- [ ] Link to that content from the "Earn Passive Rewards" page

**Comment by trentmc** [comment]
After making many other changes in the organization of DF, I don't think this will help. It's too much info about APY, too early. 

And we definitely have much bigger fish to fry than this issue. 

So, closing.
