### ISSUE TITLE
DF: Reduce READMEs and move info to design docs

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1234]
I have already taken a pretty big pass at this, but in general, READMEs are lengthy.

```
/contribute/README
/discover/README
/networks/README
/developers/ocean.py/README
```

### DoD: Data Farming & /Rewards/
- [ ] Continue consolidating info away from other pages, into design docs
- [ ] Continue consolidating info away from READMEs, into design docs
- [ ] Structure docs in a way that is more granular/compartmentalized. i.e. `/rewards/veocean/README.md`, `/rewards/veocean/time_locking.md`. 1-page per concept, or "3 concepts at a time". i.e. `/rewards/veocean/voting_power.md`
- [ ] Rename `/rewards/` => `/data-farming/`
- [ ] Replace Keanu w/ Farmers

...please add others...

**Comment by trentmc** [comment]
I just created github issues for the two most actionable items here:

- Rename `/rewards/` => `/data-farming/` --> #1320 
- Replace Keanu w/ Farmers [etc] --> #1321 

Reviewing the other concerns listed in the description, I don't see other specific opportunities. (Also note that I just did about 10 other issues to improve DF docs:)

So, closing this issue.
