### ISSUE TITLE
C2D: Add detailed C2D Flow diagram

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/docs#1238]
The new C2D detailed flow diagram is available [here](https://drive.google.com/file/d/11ZlNBHBplCCsBZNZnUGKgusZf86O2A4v/view?usp=drive_link). Please add it to the C2D architecture [chapter](https://docs.oceanprotocol.com/developers/compute-to-data/compute-to-data-architecture), (maybe after the description of all C2D components) together with a description of the flow.

**Comment by mihaisc** [comment]
@AnaLoznianu do we still want to do this? i would close this

**Comment by AnaLoznianu** [comment]
Yes, we have the diagram. It will be simple to add it

**Comment by AnaLoznianu** [comment]
Talked more with Alex and discovered a few errors in the diagram itself. We are waiting for an updated version from the designer.
