### ISSUE TITLE
Update diagrams/visuals that have a white background

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1241]
I've noticed that some visuals have a white background instead of a transparent one. While this looks fine on the light theme, it doesn't appear as pleasant on the dark theme. Please review all diagrams/visuals and include the transparent background version for each of them.

**Comment by mihaisc** [comment]
While this is nice to have, not sure we want to focus on it

**Comment by AnaLoznianu** [comment]
It's a super easy task that will bring value. I'll do it
