### ISSUE TITLE
Document DBS functionality, components & the flow

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1245]
Document how dbs works, what components is used, how to use it with the market. 

Link: https://docs.oceanprotocol.com/~/changes/JYwK6Hgokq1RhMcgfVWn/developers/dbs-decentralized-backend-storage

**Comment by EnzoVezzaro** [comment]
@jamiehewitt15 can you take a look at the docs when you have the chance please. I've done some changes to add more information.

**Comment by jamiehewitt15** [comment]
The work on gitbook needs to be moved to a github PR. I'm taking this over while you're away @EnzoVezzaro

**Comment by EnzoVezzaro** [comment]
all changes are on https://github.com/oceanprotocol/docs/pull/1256

I think we can close this issue as seems a duplicate of #1255 @jamiehewitt15
