### ISSUE TITLE
Document ocean CLI

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1258]
Let's create some documentation around the new cli built. 
I'm thinking that a page in the developers section and an user guide should be enough.
@bogdanfazakas thoughts?

**Comment by mihaisc** [comment]
One page, with some simple examples is more than enough. At the end of the day this is just a ocean.js wrapper

**Comment by bogdanfazakas** [comment]
Agreed, a simple single page with some context and examples should be fine.
also think there is a duplicate for this issue and we should stick to this and close #1254

**Comment by AnaLoznianu** [comment]
done via: https://github.com/oceanprotocol/docs/pull/1263
