### ISSUE TITLE
Duplication within FAQ & Data Farming 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1262]
### Problem
I believe the update to the FAQ page created some duplication
https://github.com/oceanprotocol/docs/pull/1253/files

### Duplicate Areas
[Issue # 1] There are 2x sections regarding Data Farming inside faq.md.
1. Data Farming
2. Data Farming FAQ

[Issue # X]
I don't know if there was duplication elsewhere, but if there are, please list them here (Issue X, Y, Z) so there is a clear list of issues to complete.

### DoD:
- [ ] All duplicate areas and issues above have been addressed
- [ ] Duplication/redundancy has been reduced

**Comment by AnaLoznianu** [comment]
Are you referring to the [Data Farming](https://docs.oceanprotocol.com/discover/faq#data-farming) and [Staking](https://docs.oceanprotocol.com/discover/faq#staking) sections? Cause there is no Data Farming FAQ section 🤔

**Comment by trentmc** [comment]
@AnaLoznianu the main DF docs include all the info on staking (and on veOCEAN). Because both of those are basically implemented as part of the overall DF program.

**Comment by trentmc** [comment]
This issue is now superseded by [docs#1265](https://github.com/oceanprotocol/docs/issues/1265) "Move FAQ content on {DF, veOCEAN, staking} into main Data Farming docs".

Therefore closing.
