### ISSUE TITLE
Linkage to pdr-intro.md#predictoor-structure is not working

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/docs#1272]
### Problem
When you try to [link an item](pdr-intro.md#predictoor-structure) the linkage compiles into a broken state.
I have tried ~4 variations on this.
```
- [link an item](../predictoor/pdr-intro.md#predictoor-structure)
- [link an item](../predictoor/pdr-intro#predictoor-structure)
- [link an item](pdr-intro.md#predictoor-structure)
- [link an item](pdr-intro#predictoor-structure)
```

None of them seem to be working in gitbook... Although they are working locally on VS Code... not sure if this is cache issue or something that I'm experiencing (tried to use private/clear cache, etc...)

I left it [linking to](pdr-intro.md) which compiles the gitbook "correctly".

### Fix linkage to #predictoor-structure
You should be able to link to the header without any issues.
![image](https://github.com/oceanprotocol/docs/assets/69865342/67f8609e-61ba-4559-b80b-c5baad49d021)

And fix the link @ `pdr-architecture`
![image](https://github.com/oceanprotocol/docs/assets/69865342/56cd8a5f-7a9a-4944-957d-8685cbf5b64a)

### DoD:
- [ ] Document links to predictoor-structure

**Comment by idiom-bytes** [comment]
This might be a local issue, I'm not sure.
Creating this issue so we can close predictoor-docs PR.

**Comment by trentmc** [comment]
This is working
