### ISSUE TITLE
DF: Add Predictoor DF content & related for Nov 9

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1289]
### Background / motivation

Predictoor DF launches on Nov 9, 2023. Budget of 37K

It also brings updates: 
- revised Volume DF budget (70K -> 37K)
- revised Challenge DF budget (5K -> 1K)

And, Challenge DF winds down 4 weeks later. 

We need to update docs accordingly.

Do #1356 first: for each DF topic, merge its "about" page and "user guide" page.

Content sources: 
- ["Introducing Predictoor Data Farming" (draft) blog post](https://blog.oceanprotocol.com/introducing-predictoor-data-farming-ad4c95f4a9aa)
- ["DF Main is Here" blog post](https://blog.oceanprotocol.com/ocean-data-farming-main-is-here-49c99602419e)

Note: [df-private#66](https://github.com/oceanprotocol/df-private/issues/66) mirrors this issue, for visibility.

**Comment by KatunaNorbert** [comment]
The draft links to already published Challenge DF introduction blogpost

**Comment by trentmc** [comment]
> The draft links to already published Challenge DF introduction blogpost

@KatunaNorbert This issue is for Predictoor DF, not Challenge DF

**Comment by KatunaNorbert** [comment]
Sure, but I think you wanted to share the link of the draft blogpost for the Predictoor DF not Challenge DF, but instead the link redirects to Challenge DF

**Comment by trentmc** [comment]
> Sure, but I think you wanted to share the link of the draft blogpost for the Predictoor DF not Challenge DF, but instead the link redirects to Challenge DF

Thanks. Link is now fixed.
