### ISSUE TITLE
Put a client redirect and 301 redirect in place for docs.oceanprotocol.com/tutorials/wallets/

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#151]
Redirect to docs.oceanprotocol.com/concepts/wallets/

1. client redirect
2. 301 redirect

The 301 redirect could be done using Cloudflare "page rules" but I wonder it there's a better way, because Cloudflare makes you pay if you want to have lots of page rules.

This issue was suggested by @kremalicious in the comments on pull request #148

**Comment by ttmc** [comment]
Maybe Gatsby already has a preferred way to handle client redirects?

It would be nice to have a single YAML file listing all redirects. Maybe there already _is_ one?

**Comment by kremalicious** [comment]
yup, I put in configurable client redirects :-) https://github.com/oceanprotocol/docs/blob/master/config.js#L22

**Comment by ttmc** [comment]
Commit https://github.com/oceanprotocol/docs/pull/148/commits/b18bef898d7f97a9e381f5018d66e3126d55f8ec (by @kremalicious ) set up a client redirect.

I'm not sure a 301 redirect is necessary, and as noted above, I don't like the idea of having to pay for one (or several, over time).

**Comment by ttmc** [comment]
I checked and we're already paying for Page Rules for oceanprotocol.com on Cloudflare, and we had 17 left in our current quota, so I created one for docs.oceanprotocol.com/tutorials/wallets/

Issue resolved.
