### ISSUE TITLE
The link to Nile Testnet no longer works

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/docs#170]
see page https://github.com/oceanprotocol/docs/blob/master/content/concepts/testnets.md
line: 28

> Technical Details about the Public Testnets
> Details about the Nile Testnet (which is called the "Parity Secret Store Cluster" on that page).

The link returns a 404

**Comment by ttmc** [comment]
The linked page was removed because it was defunct.

The link is removed in https://github.com/oceanprotocol/docs/pull/168 (not merged yet).
