### ISSUE TITLE
(Issue) Update the React App Tutorial

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#181]
...to work with the latest squid-js (for keeper contracts v0.8.x).

- [x] Page 1: Setup - updated by pull request #180
- [x] Page 2: Publish flow - updated by pull request #182
- [x] Page 3: Consume flow

**Comment by ttmc** [comment]
Pull request #182 updated the _Publish_ page in the React App Tutorial.

That leaves the _Consume_ page to update.

**Comment by santteegt** [comment]
Hi,

Is there anything I can help you with in order to update the tutorial?

**Comment by ttmc** [comment]
@santteegt There were some issues with squid-js working with the latest keeper contracts, for the Consume Flow, but I think those issues are mostly resolved now. I think we'll update the tutorial soon. We also have to update other things using squid-js, such as Pleuston.

**Comment by ttmc** [comment]
I think pull request #193 took care of this issue so I will close it.

P.S. I just noticed that page 3 of the React App Tutorial still has that **NOTICE** at the top, saying it is not currently working. I made a note to remove that.
