### ISSUE TITLE
outdated information in keeper-contracts

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/docs#210]
i found some old information on the docs: https://docs.oceanprotocol.com/concepts/architecture/#keeper-contracts

```
Token Curated Registries (TCRs) - Users create challenges and resolve them through voting to maintain registries.
Ocean Tokens - The intrinsic tokens circulated inside the Ocean Network, which is used when voting within TCRs.
Curated Proofs Market - The core component where people can transact with each other and curate assets through staking with Ocean tokens.
```

TCR & CPM are not in keeper right now.

**Comment by kremalicious** [comment]
as the link on the bottom shows, it needs to be updated in dev-ocean repo

**Comment by ttmc** [comment]
I will fix that tomorrow. Thanks for bringing it to our attention.

**Comment by ttmc** [comment]
https://github.com/oceanprotocol/dev-ocean/pull/139 fixes the above and also updates several other things.
