### ISSUE TITLE
React App Tutorial is not working, again. Some ideas...

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#212]
The [React App Tutorial](https://docs.oceanprotocol.com/tutorials/react-setup/) is not working, again. I tried it just now. It failed on the final (consume) step. Here's a screenshot of the console log.

![Screenshot from 2019-04-11 13-58-06](https://user-images.githubusercontent.com/1210951/55960997-3c56f300-5c6e-11e9-8e7c-2be5b2ff333e.png)

### Some Ideas

- Maybe we don't need the React App Tutorial any more? Maybe the squid-js examples, the squid-js tests, Tuna, the Commons Marketplace and Pleuston are enough. Let's minimize the amount of stuff we need to maintain.
- The React App Tutorial is specific to squid-js. In fact, there should be a different version of the tutorial for every version of squid-js. In other words, the React App Tutorial source code should live in the squid-js repository and it should be tested as part of the Travis tests. The docs site _can_ pull content from other repositories, so it should be possible. But what _version_ of the tutorial should be shown on the docs site? Should we give readers a squid-js version-selector? The same issue arises with the squid-js API docs, see issue #195. Putting all the squid-js docs and tutorials on their own ReadTheDocs site would be another solution; it lets readers chose the version number.

**Comment by kremalicious** [comment]
I think having a clear and concise walkthrough getting Ocean into React still is valuable instead of treasure hunting in the repos for it. I don't think there should be a version of the tutorial for different versions of squid-js. Tutorial should always use and work with the latest version.

But good idea, code sources should live in the squid-js repo, or even have their own repo with fully working and tested code. Cause importing code files is quite easy without further setup in docs: https://docs.oceanprotocol.com/test/#embedding-file-contents-from-github

**Comment by ttmc** [comment]
I tried the whole React App Tutorial again, from scratch. (I even uninstalled the MetaMask extension and then re-installed it.) I still got errors in the consume step, but they were different:

![Screenshot from 2019-04-11 16-22-52](https://user-images.githubusercontent.com/1210951/55965205-690f0880-5c76-11e9-8503-373bfe636473.png)

**Comment by ttmc** [comment]
@kremalicious I guess it would be okay to only have a React App Tutorial for the latest squid-js, at least for now. We don't have LTS versions (yet).

It's nice that we can embed source code files from other GitHub repositories in the docs. That might be enough. Maybe there could be two such files, each with lots of comments, making them tutorial-ish:

1. A bash script to set everything up
1. A single `src/App.js` file listing

**Comment by ttmc** [comment]
Sebastian shared this nice little JavaScript snippet which works today to register an asset (when running Barge with `./start_ocean.sh --latest`).

https://gist.github.com/H34D/3ad2283223b2bec558c045c541c95cb7

That is, there's no React or any other framework. Maybe this is the kind of thing we should start with in the docs. Then they can use it with React or Vue or whatever JavaScript framework they like.

**Comment by ttmc** [comment]
I'm closing this issue because two recent pull requests updated the React App Tutorial. I will test the new one, and if _it_ has problems I'll open a new issue.
