### ISSUE TITLE
Show some specific commands or code to request Ocean Tokens (in testnets)

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#284]
In the “Ocean Tokens” page, in the section titled "[Get Testnet Ocean Tokens]()", show some specific commands or code to get testnet Ocean Tokens, e.g.

- [ocean-cli](https://github.com/bigchaindb-gmbh/ocean-cli) (based on squid-java) has a command to request Ocean Tokens. [ocean-cli-py](https://github.com/bigchaindb-gmbh/ocean-cli-py) (based on squid-py) probably does too.
- [Tuna](https://github.com/oceanprotocol/tuna) can probably be used to request Ocean Tokens (using any of the squids).

Note: The Faucet on Commons Marketplace is for ETH, not OCEAN (in Nile or wherever it’s running).

**Comment by trentmc** [comment]
This exists now.
https://docs.oceanprotocol.com/tutorials/get-ether-and-ocean-tokens/#rinkeby-testnet
