### ISSUE TITLE
Change how we manage Aquarius & Brizo API references (again)?

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#286]
1. Should we continue to pull the JSON Schema spec files from live Aquarius and Brizo instances attached to Nile? Or should we switch to instances attached to Pacific? See:

    - https://github.com/oceanprotocol/docs#swagger-specs 
    - `fetchSwaggerSpec` in `gatsby-node.js` (which is where we set the URLs of the instances to use)

1. Should we continue to have (some) old Aquarius and Brizo JSON Schema spec files available at [SwaggerHub](https://app.swaggerhub.com/)? Troy is the only person able to add new ones there and others can't be added to the "team" because we're on the free SwaggerHub plan which doesn't allow for teams. It's also a very manual process to upload new old spec files there. Maybe it's not worthwhile. Maybe just remove the link to "past versions" at https://docs.oceanprotocol.com/references/aquarius/ and https://docs.oceanprotocol.com/references/brizo/

My opinions:
1. Switch to using Aquarius and Brizo instances in Pacific.
1. Don't bother with storing past versions in SwaggerHub, and remove the links to "past versions" from the docs.

**Comment by kremalicious** [comment]
1. yup agree, we need to switch everything to Pacific, it's our default main network. Should be quite straightforward switching the urls in atsby-node.js and should work as before

2. I think if we can't automate this it is doomed to be forgotten. So if no automation of that is possible I would ditch that for now.
