### ISSUE TITLE
add and explain DDO & DID in /concepts/terminology

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#326]
1-3 sentences about DDO & DID.

- https://github.com/oceanprotocol/OEPs/tree/master/7/v0.2
- https://github.com/oceanprotocol/OEPs/tree/master/8/v0.4

**Comment by kremalicious** [comment]
anything happening here?

**Comment by kremalicious** [comment]
hello?

**Comment by trentmc** [comment]
Way bigger fish to fry than this.
