### ISSUE TITLE
update architecture overview

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#330]
Our shown architecture overview is terribly outdated https://docs.oceanprotocol.com/concepts/architecture/

Update to current tech stack and create new diagrams from it. Document is sourced from dev-ocean and needs to be edited there: https://github.com/oceanprotocol/dev-ocean/blob/master/doc/architecture.md

**Comment by kremalicious** [comment]
anything happening here?

**Comment by kremalicious** [comment]
hello? What's the status of this?

**Comment by trentmc** [comment]
Heavily updated for V3. Therefore done.
