### ISSUE TITLE
Make quickstart slightly more prominent

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#448]
Goals:
- Get quickstart to be a "fast track to building"
- But only when the developer has grokked the essence of Ocean 

How:
- Move it right after 'Introduction', rather than after 'Compute-to-Data'

**Comment by trentmc** [comment]
Lol looks like @kremalicious already did this yesterday.
https://github.com/oceanprotocol/docs/commit/958d9a4bd1d5e89ecbebb91fa3486bbfdac9c460

Therefore, this ticket is done:)

**Comment by kremalicious** [comment]
Ah yes, that was included in yesterday's pushing spree into `master` somehow :-)
