### ISSUE TITLE
API Docs for squid-js

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#45]
It would be nice to have API documentation for squid-js as part of the docs site, if that makes sense.

@kremalicious You're much more familiar with the JavaScript world and the common practices around documenting JavaScript APIs, and you used squid-js when working on Pleuston, so I'll assign this issue to you.

**Comment by kremalicious** [comment]
After many more tries with various generators trying to get stuff out of squid-js: we can only go the route of going through Gatsby if we can use documentation.js. For js projects, that's the only system able to generate flat markdown files. But it only works when JSDoc comments are added to the code, at the moment squid-js doesn't have that.

TypeDoc is quite limited and by default only outputs HTML. While I was able to generate markdown from it, it's puts everything into many sub folders and files making it impossible to properly use in a maintainable way.

The other alternative is to live with the HTML generated from a project. The docs could then generate and copy the output into the right place and handle the deployment. Seeing this as the fallback route now.

**Comment by ttmc** [comment]
The suggested fallback route (copy the HTML generated from a project into the right place) would also work for squid-py.

The single HTML file could be generated by Sphinx + post-processing in the squid-py repo, it could _live_ in the squid-py repo, and it could be included in the docs repo as a submodule.

The TOC in the sidebar could have a YAML file as its source. I guess that YAML file could also be generated by tooling in the squid-py repo.

**Comment by kremalicious** [comment]
Actually, typedoc can generate a json file which we might be able to use similar to what we do with swagger:

```bash
typedoc --json path/to/output.json
```

**Comment by Pedro-vk** [comment]
After some investigation about the scope of this issue and the expected result, that's the steps to reproduce it:

- [`squid.js`] Generate a `json` file using TypeDoc.
- [`squid.js`] _(optional)_ Automatize the exportation of this `json` file and import it from *docs* repo.
- [`docs`] Read/sanitize the `json` file.
- [`docs`] Create a template to render this documentation (based on other templates).
- [`docs`] Expose _API reference_ on main documentation.

**Comment by ttmc** [comment]
Yay! :balloon: :balloon: :balloon: :balloon: :boom:
