### ISSUE TITLE
ocean.js API docs are not rendered

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#527]
Ocean.js API docs page is rendered blank: https://docs.oceanprotocol.com/references/ocean.js

**Comment by trentmc** [comment]
Hey @kremalicious now that @akshay-ap is working on docs, are you ok if this gets assigned to him to work on in coming weeks?

**Comment by kremalicious** [comment]
sure, feel free to pick up on #546 & https://github.com/oceanprotocol/ocean.js/pull/570 which together make the page generation work in #546 but many elements are still due to be accounted for on the rendered page. 

But be aware this is not a documentation writing task, but an advanced debugging & engineering task so this can be pretty time-consuming. Because everything here is [auto-generated](https://github.com/oceanprotocol/docs/blob/main/docs/apis.md#typedoc-specs) on build time. And at the end there also needs to be a new ocean.js release before this can be released on the docs.

**Comment by trentmc** [comment]
> But be aware this is not a documentation writing task

Thanks for the note. Let's assume that the label "documentation" means "for documentation" not "write stuff".

Lots of the other documentation stuff is like that too.

I'll add @akshay-ap
