### ISSUE TITLE
'contributing' section give better suggestion for branch name

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#580]
**Is your feature request related to a problem? Please describe.**

From [slack](https://bigchaindb.slack.com/archives/CNDG1849Z/p1614085571031800):

Suggestion for naming branches, that the backend core team is going to do, this would be good for all: `issueXYZ-quick-feature-descr`. The "issueXYZ" part helps to quickly reference the issue #. The "quick-feature-description" helps to quickly distinguish among the 5-10 branches that are in play at any given point in time.

For this issue: update https://docs.oceanprotocol.com/concepts/contributing/#fix-or-improve-core-software

**Comment by jamiehewitt15** [comment]
I've implemented this: https://github.com/oceanprotocol/docs/pull/604

I suggested a slash after the issue number to make it a bit clearer: `issue001/short-feature-description`
