### ISSUE TITLE
Add Travala to "Projects using Ocean"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#595]
The page https://docs.oceanprotocol.com/concepts/projects-using-ocean/

should include Travala under the "Using OCEAN" section.

More context:

https://twitter.com/oceanprotocol/status/1367108749878468613

**Comment by DimitarSD** [comment]
Any progress on this issue? @innoprenuer

**Comment by trentmc** [comment]
Looks like this issue isn't gonna happen.

There are many other projects now too. "Projects using Ocean" is not getting updated in general. I just created #700 about this.

In light of #700 existing, I'm closing this.
