### ISSUE TITLE
"Supported networks: Polygon" section links to blog post for more info

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/docs#597]
OLD scope:

We should add a small dedicated FAQ section to Polygon/Matic inside [Supported Networks](https://docs.oceanprotocol.com/concepts/networks/) to common questions users might have.

Since we won't be able to answer all questions (it's not our goal, and with adding more networks in the future it will become harder), we might need to redirect to Polygon/Matic support for more detailed questions regarding their network. Where we should redirect them? - discord?

NEW scope: 
see first comment below

**Comment by trentmc** [comment]
I'll document where we're at, from discussion in slack etc:

We decided to _not_ have a dedicated FAQ there. Rather, simply link to the blog post that lays out the info. 

Therefore, this ticket is "done" when: link is there.

Alright?

**Comment by DimitarSD** [comment]
Yep, that's the goal. I have prepared a short text for the docs, I just need the link (when it's ready) to include it and push the changes.

**Comment by DimitarSD** [comment]
I'm closing this issue since we linked the blog post to the docs
