### ISSUE TITLE
Background glitch - waves are split

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/docs#602]
The waves are split 
![image](https://user-images.githubusercontent.com/26000280/111447476-25e92a00-8716-11eb-939b-ccc73f27035d.png)
![image](https://user-images.githubusercontent.com/26000280/111447495-2a154780-8716-11eb-8d68-95e97cdb9754.png)

**Comment by jamiehewitt15** [comment]
We won't fix this as we're moving to gitbook
