### ISSUE TITLE
Fine-tune new documentation for ocean.py, aquarius, provider

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#631]
**Is your feature request related to a problem? Please describe.**
This issue had introduced new readthedocs style documentation for ocean.py, aquarius, provider.
https://github.com/oceanprotocol/multi-repo-issue/issues/80

It's now live. But there are clearly tweaks needed for both.

**Describe the solution you'd like**
Identify little issues and fix them bit by bit. Rather than documenting each individually, most of them are obvious. Eg the README should show up first thing.

**Comment by akshay-ap** [comment]
- [ ] Add source in footer of markdown
- [ ] Display all the existing markdowns in the projects `ocean.py`, `aquarius` and `provider` 
- [x] Render modules in nested way rather than flattening.
