### ISSUE TITLE
"Aquarius" and "Aquarius read the docs" in sidebar is confusing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#642]
See image below. It's confusing for Aquarius. Same for Provider.

Recommend:
- Aquarius -> Aquarius REST API
- Aquarius read the docs -> Aquarius Py module
- (same for provider)

![5](https://user-images.githubusercontent.com/5305452/118007691-a8741b80-b34c-11eb-9319-2a90f45a5d2f.png)

**Comment by akshay-ap** [comment]
![image](https://user-images.githubusercontent.com/16358982/118846850-6bb89f00-b8cd-11eb-8b46-221a96f6ea46.png)

**Comment by trentmc** [comment]
You can go ahead and close it @akshay-ap
