### ISSUE TITLE
Add subgraph api

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/docs#646]
Add api url from https://github.com/oceanprotocol/ocean-subgraph

**Comment by akshay-ap** [comment]
@mihaisc We are now rendering the subgraph readme on docs website: https://docs.oceanprotocol.com/references/read-the-docs/ocean-subgraph/. Is this fine or something more is expected for this issue?

**Comment by mihaisc** [comment]
Looks great, you are missing the urls for polygon and binance
