### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#665]
**Describe the bug**
The following link is broken: https://docs.oceanprotocol.com/tutorials/azure-for-brizo/

**To Reproduce**
1. Go to https://docs.oceanprotocol.com
2. Click on 'Tutorials'
3. Scroll down to and click 'Set Up Azure Storage'

**Expected behavior**

**Screenshots**
No "Page not found." error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 89.0.1

**Comment by trentmc** [comment]
I went to reproduce this bug. It's working now.
