### ISSUE TITLE
Update C2D docs: how to write algos & access user input

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/docs#677]
Update C2D docs:
  - how to write algos with input
  - how to access user input inside the algo

**Comment by trentmc** [comment]
The new C2D README in ocean.py makes using C2D far better. Any future things are gonna happen after V4. So in the meantime let's close all these issues out.  If you disagree then reopen and let's discuss:)
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md
