### ISSUE TITLE
"Projects using Ocean" is not getting updated

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#700]
**Is your feature request related to a problem? Please describe.**

"Projects using Ocean" page was built based on many requests from community. But we haven't been maintaining it. Even a simple thing like adding one more item is 5 months old with no progress (eg #595).

**Describe the solution you'd like**

Figure out how to move this forward, then execute.

Options:
1. Leave it as-is
2. Just deprecate, nothing more
3. Make a concerted effort to update, and put in better plans to maintain
4. Deprecate it, and start a github-based 'ocean-awesome' list with open access permissions. Initially populate with current content of "Projects using Ocean"
5. Start with (1), move to (4) when we feel more pain

Analysis: (1) is not so bad now, we could wait, and revisit. (2) loses the good content now. (3) is alright _if_ we can find the effort. (4) is more maintainable. (5) is a pragmatic combo of (1) then (4).

**Comment by trentmc** [comment]
Update: in the `site` repo @AnaLoznianu created a [similar issue](https://github.com/oceanprotocol/site/issues/1239) and suggested for @sjvallon to do it. 

I like that suggestion, assuming Sarah's game.

Therefore, here I'm assigning Sarah to the issue (please change if you feel otherwise), and closing the issue on `site` since it's redundant with this one.

**Comment by sjvallon** [comment]
There was a discussion on whether we should include the projects building on OceanDAO or not, which is how the issue came to be on the site PM board. I'm fine with updating the list this time around, but I will not be maintaining it. Instead, it can be handed over to the incoming member of the MarComm team if no one else is up for the task.

**Comment by trentmc** [comment]
> There was a discussion on whether we should include the projects building on OceanDAO or not

"Building on OceanDAO" is not accurate. They are "building on Ocean" and "funded by OceanDAO". This makes it obvious that such projects should be in "Projects using Ocean Protocol" page.

> I'm fine with updating the list this time around, but I will not be maintaining it. Instead, it can be handed over to the incoming member of the MarComm team if no one else is up for the task.

Yep no one else is going for it. So handing to the incoming member sounds like a good plan! This is an important page because it showcases many of the great things that the Ocean community is doing.

**Comment by sjvallon** [comment]
Cool. It will be updated by the end of next week.

**Comment by kremalicious** [comment]
Who is going to work on this? If noone will as nothing happened here for 2 months, then please close

**Comment by trentmc** [comment]
lol no one is working on the "no one is working on" issue

New datapoint: oceanpearl.io is a much better list now anyway. 84 teams and counting. Browsable.

Also, Ocean Market lists projects using Ocean Market, just browse the datasets. 

And, coingecko lists where people can trade OCEAN. Some of those have liquidity mining opportunities, or other yield opportunities.

Therefore, new option (6): change this page's content to point to oceanpearl, Ocean Market, and coingecko, and deprecate all the specific content. Then it's easy to maintain.

I'm doing it now.
