### ISSUE TITLE
Issue: "FRE" hard to understand. Proposal: Create a Glossary

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#717]
We should create a glossary of all of the terms and acronyms that are specific to Ocean Protocol. This issue is inspired by a user asking on Discord what "FRE" means.

Part of the process should also involve considering if all of the acronyms make sense, for example, "FRE pricing" can easily get confused with "Free pricing" which has been introduced more recently.

**Comment by jamiehewitt15** [comment]
@trentmc I like the proposal, it's simple and maintainable like you say. If we can keep all of our labels easy to understand our users will be happy, no one really wants to have to spend time reading a glossary. 

Review:
In terms of doing a review, I would suggest a very simple test that each term needs to pass - it should be possible for the user to find out the meaning in one Google search. So for example, if a user searched "Ocean Protocol Aquarius" the user will immediately find out what Aquarius is. By contrast, searching for "Ocean Protocol FRE" doesn't give any results about fixed-rate exchange pricing.  

Maintianing:
In addition to doing a review, we can ensure that we keep all labels easy to understand by doing the following:
- Avoid making up our own acronyms. This is the best way to avoid ending up in the Nortel phone book situation. Elon Musk articulates the issue with acronyms very nicely in a company-wide [email to SpaceX](https://gist.github.com/klaaspieter/12cd68f54bb71a3940eae5cdd4ea1764). 
- Avoid abbreviations. To avoid confusing customers, we should make sure a name or label is always consistent. Abbreviations are highly likely to fail the google search test above. So for example, we should make sure Aquarius is never referred to as "Aqua" anywhere in the documentation

**Comment by trentmc** [comment]
Sounds good to me.

BTW we were trying to get rid of the label "Aquarius" too, to simply make it "Ocean Metadata Cache" but it was so embedded in so many places, and super high effort to fix, we left it alone.

We _did_ however manage to get rid of a bunch of other crazy labels. Squid, pleuston, x, y, z, a, b, c.

**Comment by jamiehewitt15** [comment]
That's great, sounds like we've already made progress then. I've never heard of Squid or pleuston

**Comment by trentmc** [comment]
BTW I wasn't aware of [Elon's email](https://gist.github.com/klaaspieter/12cd68f54bb71a3940eae5cdd4ea1764). It's beautiful.

Perhaps we should share that org-wide as a suggested policy going forward.

**Comment by jamiehewitt15** [comment]
Yeah, the email is great and easy to relate to. Particularly the point that "people don't want to seem dumb in a meeting, so they just sit there in ignorance. " I think it makes a lot of sense as an org-wide policy.

**Comment by trentmc** [comment]
Thanks. Shared in slack now in #eng-main

**Comment by kremalicious** [comment]
The better solution is to not have a need for a glossary as Trent pointed out. So for “FRE” the better solution is to just never use that, which we pretty much follow in all user communication. At no point in time did we named it FRE but always “fixed price”. How this then works in detail as an exchange is not meant for a glossary but has to be explained in our main architecture. So closing this here as there was nothing happening on it for over 2 months
