### ISSUE TITLE
automate Swagger json updates

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#74]
For Aquarius and Brizo we need to find a way to get the most recent Swagger spec as json into the docs build process. At the moment they simply live as manually copied json files in `/data`.

Ideally, the json file just sits in the original repository, and is updated automatically during every release process. During docs build process I can then either get it through GitHub GraphQL API, or a normal fetch.

We could also fetch it remotely from somewhere else, a Swagger client is already in the docs site.

**Comment by ttmc** [comment]
Handy tip for now: We have some live, online Aquarius instances and you can ask those for the Swagger spec (i.e. something like `data/aquarius.json`). For example, see https://nginx-aquarius.dev-ocean.com/spec 

Unfortunately, that JSON is not exactly what the docs site wants. Even after I add the top-level "basePath" and "host" fields to it, errors arise.

**Comment by kremalicious** [comment]
fetching them remotely would be actually nice, already doing that with the Pet Store example https://github.com/oceanprotocol/docs/blob/master/gatsby-node.js#L41
