### ISSUE TITLE
Update Fine-grained Permissions Docs

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#749]
The communication around the fine-grained permissions have been refined in the blog post and the documentation should be updated to reflect this. 

The draft blog post is here. #668 is the issue to publish the blog post.
https://docs.google.com/document/d/1fsYgoI_gJnP_paTajuXvUIB4oYqVfZ4vczea3LH0kVI/edit#heading=h.ay5012evkgpk

**Comment by trentmc** [comment]
Re-assigning back to Jamie since he's got a PR in progress for it.
https://github.com/oceanprotocol/docs/pull/750

I just reviewed it. It's got a good start. There are still some changes needed.
