### ISSUE TITLE
Aquarius docs page isn't useful for external contributors

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/docs#751]
See this page: https://docs.oceanprotocol.com/references/aquarius/

- No reference to production endpoints
- Unclear what data structure is returning
- Unclear what Aquarius version is running online and what the API is referring to

**Comment by trentmc** [comment]
> Either way, it should be an issue in docs and not Aquarius repo. I don't know how this ended up here :)

OK, I just transferred from Aquarius repo to docs repo.

**Comment by trentmc** [comment]
> If there is something else I need to do, please let me know. Otherwise, we can close this

I just reviewed everything here. It seems we're OK for this issue. In one case some work is now in https://github.com/oceanprotocol/aquarius/issues/538 which is partly done. And there are a couple other aqua doc tickets to handle.

Tim if you see remaining things that you consider the scope of this issue feel free to comment and reopen if needed.
