### ISSUE TITLE
In concepts > quickstart, the ocean.js link goes to API, it should go to ocean.js README

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#764]
**Describe the bug**

To reproduce:

1. Go to https://docs.oceanprotocol.com/concepts/quickstart/
2. Click on "ocean.js"
3. It takes you to to https://docs.oceanprotocol.com/references/ocean.js/

(3) is wrong because that's not a quickstart, it's an API reference (not the best thing to quickly gets started with). 

Also: there's a link to React quickstart. That's no longer supported, so we should remove it.

**Expected behavior**
Step (3) should take you to https://github.com/oceanprotocol/ocean.js/blob/main/README.md

Also: there should be no link to React at all.

**Comment by akshay-ap** [comment]
The quickstart page also refers to Ocean React which is now deprecated. I think we should remove the Ocean React reference.

**Comment by trentmc** [comment]
> I  think we should remove the Ocean React reference.

Agreed. Go ahead and remove it here. I will update this issue's description to be in line with that, so you can have it all in one PR

**Comment by akshay-ap** [comment]
> 
> 
> > I  think we should remove the Ocean React reference.
> 
> Agreed. Go ahead and remove it here. I will update this issue's description to be in line with that, so you can have it all in one PR

done
