### ISSUE TITLE
Possible improvements to c2d tutorial

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/docs#770]
I recently ran through the c2d tutorial: https://docs.oceanprotocol.com/tutorials/compute-to-data-algorithms/ and I think we can make some improvements:

- a few lines about creating a docker image and how to determine the algo entrypoint in the case of each image. E.g. I had trouble realising why some Python images have `python3.6 $ALGO`, and others `python $ALGO`
- clarify structure of `/data/inputs`, `/data/ddos` with examples and what they represent. This is something the user can debug based on the Python example, but it's nice to be helpful. E.g. I had some trouble determining that the structure of the inputs folder is different from the ddos one, and that the path for an input file is `data/inputs/{did}/{service_id}'.
- when the docker image does not exist, the output log is empty, but the job shows up as finished. Is there any way to output a useful error message? E.g. "docker image not found" in the output log? A simple typo can waste hours. It happened to me when I put "python-pandas" instead of "python-panda" as the image tag, on the assumption that the image is named after the pandas package.

I can work on this if someone green lights it.

**Comment by kremalicious** [comment]
this all sounds great, anything which makes this more clear is good. Also remember having lots of trouble figuring out everything around what algorithms expect and such. And short explanation on how to get custom Docker image would be great too including maybe links to our custom Docker images, e.g. I used this https://github.com/oceanprotocol/algo_dockers/tree/main/node-vibrant for this https://market.oceanprotocol.com/asset/did:op:38D471eC06d2bA6DF6Fd14E48268CABFe6d2bF1C

**Comment by alexcos20** [comment]
we could extend https://docs.oceanprotocol.com/tutorials/compute-to-data-algorithms/

**Comment by kremalicious** [comment]
Is this considered finished? What’s the difference to #714?

**Comment by trentmc** [comment]
The new C2D README in ocean.py makes using C2D far better. Any future things are gonna happen after V4. So in the meantime let's close all these issues out.  If you disagree then reopen and let's discuss:)
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md
