### ISSUE TITLE
Step-by-step guide on forking and customising Ocean Market

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#773]
### Overview
This issue is inspired by a partner requesting a meeting to walk them through the process of forking the market. In the future, there will be many more teams requiring help with this so I suggest we provide a more detailed walk-through of the process in our documentation. 

### Issue
Currently, our [documentation](https://docs.oceanprotocol.com/tutorials/marketplace/) suggests forking the market and provides a link to the Github repo. However, this is of very limited help because there are many basic things that are not documented in the repository readme. For a new team, they may be left with some simple questions such as "How do I change the logo?" which would be best covered in the documentation. 

![Fork the market](https://user-images.githubusercontent.com/20739535/134499029-8e670e46-b35a-42c9-aa7e-92c8fa44264f.png)

### Proposed solution
A full beginner friendly step by step walkthrough on how to set up and customise Ocean Market. It should cover: 

- [ ] How to fork the market on Github & how to clone the market via Git cli
- [ ] How to change the name/title of the market
- [ ] How to change the logo
- [ ] How to change the font - this is important as our font is copyright protected 
- [ ] Change the styles and colours
- [ ] Introduction to the feature toggles - what they do and how to change them. 
- [ ] How to build and deploy the market

### Extension 

This would also make a good topic for a blog post. Related issue: https://github.com/oceanprotocol/privateissues/issues/40

**Comment by kremalicious** [comment]
> However, this is of very limited help because there are many basic things that are not documented in the repository readme

so the correct solution then is to update the readme. We will never manage to update readme, docs and blog post for the same thing when we refactor market every month. The blog post is nice but will be outdated pretty quickly and then it just disappears for most users in the myriad of other blog posts

**Comment by trentmc** [comment]
I agree with focusing on the README.

Also, we could also publish as a blog post to raise initial awareness. And at the top, say "an up-to-date version of this guide is at ___". Best of both worlds:)

**Comment by jamiehewitt15** [comment]
@kremalicious I get your point around maintaining it in two places. The intention behind this is essentially to write an in-depth tutorial for people forking the market. I think the readme may become quite bloated if everything gets added there, we could put it inside the `./docs` folder on the market repository

**Comment by jamiehewitt15** [comment]
The marketing team are very keen for more content from the tech team so I think they will be grateful if a blog post is still written as part of this

**Comment by jamiehewitt15** [comment]
The blog post that I'm suggesting this documentation should be based on is [here](https://blog.oceanprotocol.com/launch-a-blockchain-based-data-marketplace-in-under-1-hour-9baa85a65ece). It will be a fairly small amount of effort to convert it to markdown and make it a bit more concise for the docs. It can go either here or in `market/docs`.

@trentmc @kremalicious is this worth doing now or should we wait until the updated V4 version of the market is released?

**Comment by trentmc** [comment]
I believe its bang-for-buck is worth it to do soon. We could have @akshay-ap potentially do it as well.

**Comment by kremalicious** [comment]
I will always say no to things which have nothing to do with v4. Why now duplicate this post which should have been a tutorial in the docs from the beginning. The whole v4 market codebase is already completely different so if we no create the tutorial in docs too, we then have created the need to update 2 tutorials in 2 places when launching v4. Besides telling people to fork the market now will create a lot of frustrations when launching v4 as there will be no migration path for them.

If you ask me all work on anything to do with v3 needs to stop. The only important things on docs right now need to be tackled instead which is also really important for us internally:

- https://github.com/oceanprotocol/docs/pull/783
- https://github.com/oceanprotocol/docs/pull/780
- all going into https://github.com/oceanprotocol/docs/pull/819

**Comment by trentmc** [comment]
> Besides telling people to fork the market now will create a lot of frustrations when launching v4 as there will be no migration path for them.

This is an especially good point. Given this, ok with me to hold off until after v4.

> The only important things on docs right now need to be tackled instead which is also really important for us internally ...

@akshay-ap please take note, these items would be good to look at (and reconcile your work with that of others working on v4).

**Comment by jamiehewitt15** [comment]
Yeah, fair enough let's hold off until the V4 market is available. 

> Why now duplicate this post which should have been a tutorial in the docs from the beginning?

The reason it was posted as a blog post on Medium is that medium reaches a different audience vs GitHub documentation.

**Comment by AnaLoznianu** [comment]
@jamiehewitt15 Can we close this as we are working on integrating the marketplace launchpad content?

**Comment by jamiehewitt15** [comment]
Yeah, this issue is a duplicate of: https://github.com/oceanprotocol/docs/issues/1010
