### ISSUE TITLE
DID structure doc is incomplete

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/docs#785]
https://docs.oceanprotocol.com/concepts/did-ddo/#did-structure

It's nonsufficient to just slice 0x from an address if that address isn't checksummed according to EIP55 https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

Hence, the docs should mention that before pretending `op:did`, any address must be checksummed.

E.g. see the lowercased version of 

- https://market.oceanprotocol.com/asset/did:op:7bce67697ed2858d0683c631dde7af823b7eea38
- https://market.oceanprotocol.com/asset/did:op:7bce67697ed2858d0683c631dde7af823b7eea38

**Comment by AnaLoznianu** [comment]
Closing this as we've updated the DID&DDO info for V4: https://docs.oceanprotocol.com/concepts/did-ddo/#ddo-checksum & https://docs.oceanprotocol.com/concepts/did-ddo/#did
