### ISSUE TITLE
coc email is bouncing

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/docs#799]
referring to this document: https://github.com/oceanprotocol/docs/blob/5292f0de8f4a21f201a7a6d41100ffeb4202ae5e/content/concepts/code-of-conduct.md

when sending an email to conduct@oceanprotocol.com, the email bounces. pls update email thx

**Comment by akshay-ap** [comment]
hi @TimDaub, we test the email and it looks to be working now.
So, if that is ok for you we can close this issue.
