### ISSUE TITLE
Aqua V4 Docs

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#850]
- [x] Update the destination URL when we generate from the V3 branch
- [ ] Add V4 specific documentation

**Comment by calina-c** [comment]
@akshay-ap 
Regarding the 1st point, we want to have the docs for v3 in another place but I have no specific details. It will probably be under https://docs.oceanprotocol.com/v3/

Regarding the second point, in addition to reviewing the ENV params, also the docstrings, params and purpose of the functions should also be looked into. I can help and advise if necessary, but for the most part it's straightforward. Ping me on Slack if you encounter any difficulties.

**Comment by akshay-ap** [comment]
@calina-c , we have another [issue](https://github.com/oceanprotocol/docs/issues/859) for discussing how we will keep `v3` and `v4` docs going forward.
