### ISSUE TITLE
Docs landing page after v4 launch

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#859]
**Is your feature request related to a problem? Please describe.**
As discussed with @alexcos20 , we plan to keep v3 docs along with v4. We need to update the front page of docs so that users can see a clear segregation between v3 and v4 docs. 

**Describe the solution you'd like**
Proposal 1:
- update docs page as below: 
![image](https://user-images.githubusercontent.com/16358982/149289017-13f9884b-be1e-491f-ad56-6b5231131fbe.png)

 - `v3` section will point to `https://v3.docs.oceanprotocol.com`
 - `v4` section will point to `https://v4.docs.oceanprotocol.com` or `https://docs.oceanprotocol.com/`

Benefits:
- Easy to point users to different versions of docs
- Easy to maintain as we have two branch in github i.e. main for `v3` and `v4main` for v4.

**Describe alternatives you've considered**
Yet to be proposed

**Additional context**
Part of #781

**Comment by akshay-ap** [comment]
@trentmc your feedback will be helpful.

**Comment by trentmc** [comment]
It has to be different than this.

In 6-12 months, v3 will be obsolete. 

We should default to v4, which is like what you have built. It has most of the content that we had in v3, plus the extended stuff for v4 (data nft etc). It is _not_ just the new stuff for v4. This would live at docs.oceanprotocol.com.

Then there should be a way to find v3 docs. This would live at e.g. v3docs.oceanprotocol.com.

To switch between: I like how uniswap v1<>v2 worked. That is: at the top right, there's a toggle button between v3 and v4. See image below.
![uniswap-v1-v2](https://user-images.githubusercontent.com/5305452/149300179-f880ee3a-5539-4b6f-8f6f-d1869f151038.png)

**Comment by mihaisc** [comment]
You can handle it how we handle the market. Two branches (or two repos if it's easier for you) deployed on 2 urls (market.oceanprotocol.com and marketv3.oceanprotocol.com , or something similar) . And have a simple link in a corner to the old version

**Comment by akshay-ap** [comment]
From #865: 

https://deploy-preview-865--docs-oceanprotocol.netlify.app/

Home page:
<img src="https://user-images.githubusercontent.com/16358982/149909275-b004a384-7b74-480a-b537-64460680f595.png" width="400" />

Header in all other pages:

![image](https://user-images.githubusercontent.com/16358982/149910275-c30be00c-8c0a-47b2-b9dd-c7f1676ecb36.png)
