### ISSUE TITLE
[v4] "DDO specs" image font is too small / low-res, can't read it

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#888]
**Problem**

(I observed this in [this PR](https://github.com/oceanprotocol/docs/pull/882) for [this issue](#885). Maybe it's already in the main V4 branch too.)

Here's the issue: in the docs' "DDO specs" page, section "Publishing & Retrieving DDOs", there's an image with subtitle "DDO flow". But the font is too small to read / it's low-res. Here's a copy-and-paste of the image.
![ddo-flow](https://user-images.githubusercontent.com/5305452/153754840-2ee086cd-16d8-451f-ac77-c3774debb7b3.png)

Alas, there is no way to get a more high-res font. I tried to click on it, but it doesn't zoom. I used the browser to "open image in new tab", but it remains low-res.

**Describe the solution you'd like**
Make it possible to read the font somehow. Eg re-render with higher resolution, and upload that. Make sure that the high-res image doesn't swamp the page.

**Comment by akshay-ap** [comment]
This is because of a gatsby plugin that we use.
Configuration here: https://github.com/oceanprotocol/docs/blob/131c95da5aa6811c035b8123f13bc7d39fbf2a03/gatsby-config.js#L69

Checking further for the solution.
