### ISSUE TITLE
V4 - Update "Introduction" page

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#909]
We should update the "[Introduction](https://deploy-preview-819--docs-oceanprotocol.netlify.app/concepts/introduction/)" page as well. thinking especially at these paragraphs:
* "In Ocean Protocol, each data service gets its own [ERC20](https://github.com/ethereum/EIPs/blob/7f4f0377730f5fc266824084188cc17cf246932e/EIPS/eip-20.md) datatoken. This enables data wallets, data exchanges, and data co-ops by directly leveraging crypto wallets, exchanges, and more.".
* "Publish and consume data services: downloadable files or compute-to-data. Use Ocean to deploy a new ERC20 datatoken contract for each data service, then mint datatokens."
* "And more. Use ERC20 support in [web3.js](https://web3js.readthedocs.io/), [web3.py](https://web3py.readthedocs.io/en/stable/examples.html#working-with-an-erc20-token-contract) and Solidity to connect datatokens with crypto wallets and other DeFi services."
Now that we'll have ERC721

**Comment by trentmc** [comment]
A good source of content with revised wording:

The updated whitepaper. Eg the abstract.

https://docs.google.com/document/d/1dZsNiyaYoiqOM7MRdgmuBmCbFyV7DWMUrjNHSYDPMX4/edit#heading=h.gjdgxs
