### ISSUE TITLE
Update "Market" tutorial section

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#912]
As the V4 Market UI looks different from the V3 version, we'll need to update the [publish tutorial](https://deploy-preview-819--docs-oceanprotocol.netlify.app/tutorials/marketplace-publish-data-asset/).
@akshay-ap Will give you everything needed once we have a stable version of Market V4

cc @kremalicious

**Comment by akshay-ap** [comment]
- [x] V4 Publish tutorial
- [x] V4 Consume tutorial
- [x] V4 Swap tutorial
- [x] V4 Stake tutorial
