### ISSUE TITLE
V4: Update API reference for Ocean.js and Ocean.py

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#921]
- [ ] Ocean.js - https://github.com/oceanprotocol/ocean.js/releases/tag/v1.0.0-next.32
- [ ] Ocean.py - https://github.com/oceanprotocol/ocean.py/releases/tag/v1.0.0-alpha.1

**Comment by trentmc** [comment]
> On the API pages for these two components we just have a replication of the read.me and also methods and parameters extraction from the repos. This is not very useful.

This is a very strong assumption. The assumption for the last 9ish months has been the opposite: expose all the methods in a nicely formatted way as a means for people to learn about the interfaces of ocean.py and ocean.js. (And in fact this is the only current way, save for the READMEs for key use cases, and looking at the code itself).

I recommend: do _not_ the actions recommended by this ticket until we all agree, one way or the other.

**Comment by AnaLoznianu** [comment]
@akshay-ap After a discussion with @trentmc and @alexcos20 we decided to not remove the API references but instead, add proper documentation so the generated files are more useful to our users.

**Comment by AnaLoznianu** [comment]
@akshay-ap We can update the Ocean.js docs with this release: https://github.com/oceanprotocol/ocean.js/releases/tag/v1.0.0-next.29

@alexcos20 @calina-c @mariacarmina @md0x @DMats When can we have an ocean.py release?
