### ISSUE TITLE
Fix overflows in main page

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#946]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/16358982/161736898-0c967cac-2f28-43b4-922c-cc53de381ac5.png)

**Describe the solution you'd like**
No overflows

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jamiehewitt15** [comment]
Not relevant in gitbook
