### ISSUE TITLE
Page about file requirements

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#954]
Page describing what requirements there are for publishing files into Ocean Market.

From frontend side impossible to detect "valid" files during publish process, and once a file is published it can't be changed potentially leading to money loss for publishers. So informing publishers about exact requirements for hosting, and requirements for files for all asset types is crucial as we can't explain this all in the UI. Could use some quick examples for most popular hosting, like Google Drive, Azure, AWS, IPFS

See e.g. https://github.com/oceanprotocol/market/issues/1319 or https://github.com/oceanprotocol/market/issues/1246

**Comment by akshay-ap** [comment]
Proposal 1:

Add new page here:

![image](https://user-images.githubusercontent.com/16358982/165284590-023cce40-5edb-4479-9df5-d23e063a097d.png)
