### ISSUE TITLE
Rectangles everywhere

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#955]
Not sure what happened here or what the intention was, seems somebody tried to use characters which are not present on every machine:

<img width="732" alt="Screen Shot 2022-04-07 at 14 24 52" src="https://user-images.githubusercontent.com/90316/162209256-02df1cd5-e617-4817-b171-774dc22ae75f.png">

on https://docs.oceanprotocol.com/concepts/roles/ with Safari on macOS 12.3.1 with `en-US` locale

Same for https://github.com/oceanprotocol/docs/blob/main/content/concepts/roles.md which has more funky characters:

<img width="974" alt="Screen Shot 2022-04-07 at 14 27 27" src="https://user-images.githubusercontent.com/90316/162209772-99cf528c-4af7-4e85-8732-2284ceb76ae9.png">

And then the markdown file also just has rectangles:

<img width="733" alt="Screen Shot 2022-04-07 at 14 28 08" src="https://user-images.githubusercontent.com/90316/162210065-5901065c-a9a4-4c13-b19a-81c887ac1417.png">

**Comment by mihaisc** [comment]
work ok in edge(chromium) 
![image](https://user-images.githubusercontent.com/26000280/162216448-964ddc83-a089-4de2-a896-1d0a11aaef0c.png)

**Comment by bogdanfazakas** [comment]
This should be related i guess to the OS, on my end doesn't not work on any browsers on macOs

**Comment by kremalicious** [comment]
Firefox, macOS:

<img width="718" alt="Screen Shot 2022-04-07 at 14 59 17" src="https://user-images.githubusercontent.com/90316/162216756-55adb7a4-ba7a-4f6a-ac01-bb57f21453d9.png">

Chrome, macOS:

<img width="729" alt="Screen Shot 2022-04-07 at 14 59 57" src="https://user-images.githubusercontent.com/90316/162216914-165f18fd-76ef-4a78-b718-c9f2930c42c2.png">

So yes, does not work on macOS, iOS, or iPadOS. Also checked on Linux on Ubuntu and Raspberry OS and also not working there.

**Comment by mihaisc** [comment]
> this is wrong. This applies to iOS or iPadOS but was never the case on macOS

my bad

Works ok on win 11/firefox .

So it seems it's an issue regarding the charset or something

**Comment by akshay-ap** [comment]
@kremalicious We use ✓ in https://docs.oceanprotocol.com/concepts/did-ddo/ so using the same in roles page here #958. I think this will resolve the problem.
