### ISSUE TITLE
remove branch/deployment split-up

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#959]
Current `v4` branch is by now deployed as the main thing to docs.oceanprotocol.com so no need to have a `main`, `v4`, and `v3` branch. 

I see those branches and it's completely unclear for what they are used:

- `v4` (set to default)
- `v3`
- `main`
- `v4main`

Please clean this up so that we end up with only `main` & `v3` where `main` deploys to docs.oceanprotocol.com, and `v3` deploys to `v3.docs.oceanprotocol.com`. And `main` needs to be the default branch again.

**Comment by AnaLoznianu** [comment]
The branches are cleaned up now. Main is the V4 version and there is also v3
