### ISSUE TITLE
Consume used instead of download

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#960]
We decided some time ago to not expose the word "consume" as nobody talks like that. Ever said "I consume this file"? Probably not, cause it sounds weird so let's not be weird.

Throughout the whole docs it should say "download" or "run algorithm", but never "consume". E.g. this tutorial needs changed copy & URL slug, as it only talks about download it should say that https://docs.oceanprotocol.com/tutorials/marketplace-consume-data-asset/

**Comment by akshay-ap** [comment]
We have now removed the use of word `consume`.

We still we use `consumer` at certain places. I think `consumer` word is acceptable under certain context in the docs.
Should we even remove `consumer`?
