### ISSUE TITLE
Lots of 404

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#968]
Based on Netlify stats, there were quite a lot of 404's within last 30 days alone:

<img width="621" alt="Screen Shot 2022-04-13 at 11 58 17" src="https://user-images.githubusercontent.com/90316/163166130-38228c01-d69b-4781-b715-959fb55f3225.png">

Please check all of them, and as usual when changing URLs, make sure to add proper redirects, ideally 301 but user being redirected is most important. This has to be done ALWAYS when renaming actual URL paths which seem to have happened a lot in last months.

This might help for getting redirects done within the normal authoring flow: https://github.com/kremalicious/gatsby-redirect-from

You can of course ignore the php stuff (people trying to hack us assuming we use WordPress) and `.well-known/` (Let's Encrypt SSL certificates)

**Comment by akshay-ap** [comment]
hi @kremalicious,

1. https://docs.oceanprotocol.com/ -> We already have redirection to domain https://docs.oceanprotocol.com
2. https://docs.oceanprotocol.com/tutorials/permissions/asset-level-permissions -> Page does not exists. 
3. https://docs.oceanprotocol.com/tutorials/permissions/market-level-permissions  -> Page does not exists. 
4. https://docs.oceanprotocol.com/tutorials/ -> redirection works but site report 404 and then redirects to https://docs.oceanprotocol.com/tutorials/introduction/
5. https://docs.oceanprotocol.com/concepts/ddo-metadata/ -> Page exists but on hard refresh give 404 but, on reload it works. Strange!
6. URLS with `/references/read-the-docs/ocean-py/**` -> 404 occurs for a brief moment and then the content is loaded. I could reproduce it using `ctrl+f5` i.e hard refresh on mozilla firefox.
![cinnamon-20220413-3](https://user-images.githubusercontent.com/16358982/163194329-6dc52b7d-8509-40a2-8e8d-c7e484a14cd3.gif)
This also occurs when docs load the first time (as shown in gif above).

`1` - I think we can ignore
`2`, `3` - we can create redirections but where should redirection go?
`4`, `5`, `6` - Looks like this has something to do with gatsby for .

**Comment by akshay-ap** [comment]
#978 mitigates the issue to some extent but not completely. Still there is 404 but user does not notice it.

Another solution we can try: use [gatsby-plugin-create-client-paths](https://www.gatsbyjs.com/plugins/gatsby-plugin-create-client-paths/) but this requires gatsby version 4.x and we currently use 2.x.
@kremalicious can we consider upgrading to gatsby 4 (Gatsby 2 maintenance window already closed on April 1, 2021)? https://github.com/gatsbyjs/gatsby/blob/d21fc26a811178e41dd3998e64b5946c2f7abc9d/README.md#contributing-to-gatsby-v2
