### ISSUE TITLE
Write a section on the "risks" of trading datatokens and adding liquidity

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/docs#976]
We need a new section on the "risks" associated with trading datatokens and adding liquidity to pools. In the market (in both the pool tab and the trade tab) we are linking to an outdated 2020 [article](https://blog.oceanprotocol.com/on-staking-on-data-in-ocean-market-3d8e09eb0a13) about the risks of rug pulls (which we've solved). 

We need something new to link to from the market and I think it makes sense for it to sit within the docs, rather than a blog post.

Trade tab:
![Risks 1 - 2022-04-28_13-56](https://user-images.githubusercontent.com/20739535/165737941-32887c9d-2f65-401a-994e-a1bcd9c2c039.png)

Pool tab:
![Risks 2 - 2022-04-28_13-56](https://user-images.githubusercontent.com/20739535/165737967-7da665f4-a6c9-4059-a978-644a20dc95f8.png)

**Comment by AnaLoznianu** [comment]
Closing this as we removed the risks view from the trade and pool tab.
