### ISSUE TITLE
Grammar issues in `consumerParameters` section

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/docs#982]
https://github.com/oceanprotocol/docs/blame/main/content/concepts/did-ddo.md#L135
> An object the defines required consumer input...

"the" should be "that"

---

https://github.com/oceanprotocol/docs/blob/main/content/concepts/did-ddo.md#consumer-parameters
The Consumer Parameters section makes heavy use of the word "you" and "your" which results in ambiguous sentences. Is "you" the publisher? or the consumer? compute provider?

**Comment by alexcos20** [comment]
Feel free to open a PR and fix it
