### ISSUE TITLE
Consume fee for Ocean community should be 0.03 DT, not 0.3 DT

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#986]
**Describe the bug**
In https://docs.oceanprotocol.com/concepts/fees/#ocean-community-fee, it says:

"The Ocean Community order fee is 0.3 DT per order operation."

This is incorrect. It should be 0.03 DT. 

Details: 
- [Source GDoc has 0.03 DT](https://docs.google.com/document/d/1SufCXSWCUMN-x1d8hZY-7-JwUz-qzeBG-B081WfKNz4/edit#)
- Logically, it should be 0.03 DT. 0.3 DT is 30%, way too high. Whereas 0.03 DT is 3%, the amount chosen to avoid DF wash trading.

**Comment by mihaisc** [comment]
Can confirm, [subgraph query](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20opc(id%3A1)%7B%0A%20%20%20%20swapOceanFee%0A%20%20%20%20swapNonOceanFee%0A%20%20%20%20approvedTokens%0A%20%20%20%20consumeFee%0A%20%20%20%20id%0A%20%20%7D%0A%7D)
